>Rodent | XP_048289633.1 LOW QUALITY PROTEIN: Y-box-binding protein 1-like [Myodes glareolus]
MSTGIWSILDGVGIADGCKRLDMGATNQPSPGRTSGLSSYKGGLESWSTQSQKQSSELAY
PSIHPTYELLEHPELQNLHDTGQHDVHLLVDPWRTQQKPEASNHTTDSLQEAKSHEEQLS
KESLSTRRIWPSSIGSGSGERTPESPESPAAAGPSHHHRNHEQRGPAVALSAADTKPG--
---STXGSPGGLTSAAPTGGDKKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTA
IKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPR
RRGPPRNCQQNYQNSESGEKNEGSEGAPEGQAQQRRPYRRRRFPPYYVRRPYGRRPQYSN
PPVQGEVMEGADNQGAGEQGR-PVRQNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGD
ETQGQQPPQRRYRRNFNYRRRRPENPKPQDGKETKAADPPAENSSAPEAEQGGAELMPAY
HLYHHPVWSSNKKKRIXX
>Rabbit | XP_058535856.1 Y-box-binding protein 1 isoform X2 [Ochotona princeps]
------------------------------------------------------------
------------------------------------------------------------
-------------MS--SEAETQQPPAAP---------------PAAPALSAADTKPGTT
GSGAGSGGPGGLTSAAPAGGDKKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTA
IKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPR
RRGPPRNYQQNYQNSESGEKNEGSESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSN
PPVQGEVMEGADNQGAGEQGR-PVRQNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGD
ETQGQQPPQRRYRRNFNYRRRRPDNPKPQDGKETKAADPPAENSSAPEAEQGGAE-----
------------------
>Bat | XP_037005274.2 Y-box-binding protein 1 isoform X1 [Artibeus jamaicensis]
------------------------------------------------------------
------------------------------------------------------------
-------------MS--SEAETQQPPAAP---------------PAAPTLSATDTKPGTT
GSGAGSGGPGGLTSAAPAGGDKKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTA
IKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPR
RRGPPRNYQQNYQNSESGEKNEGSESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSN
PPVQGEVMEGADNQGAGEQGR-PVRQNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGD
ETQGQQPPQRRYRRNFNYRRRRPENPKPQDGKETKAADPPAENSSAPEAEQGGAE-----
------------------
>Dog | XP_005618292.2 Y-box-binding protein 1 [Canis lupus familiaris]
------------------------------------------------------------
------------------------------------------------------------
-------------MS--SEAETQQPPAAPA-------------APAAPALSAADTKPGTT
GSGAGSGGPGGLTSAAPAGGDKKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTA
IKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPR
RRGPPRNYQQNYQNSESGEKNEGSESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSN
PPVQGEVMEGADNQGAGEQGR-PVRQNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGD
ETQGQQPPQRRYRRNFNYRRRRPENPKPQDGKETKAADPPAENSSAPEAEQGGAE-----
------------------
>Lemur | XP_045401658.1 Y-box-binding protein 1 isoform X2 [Lemur catta]
------------------------------------------------------------
------------------------------------------------------------
-------------MS--SEAETQQPPAAP---------------PAAPALSAADTKPGTT
GSGAGSGGPGGLTSAAPAGGDKKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTA
IKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGIPVQGSKYAADRNHYRRYPR
RRGPPRNYQQSYQNSESGEKNEGSESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSN
PPVQGEVMEGADNQGAGEQGRPPVRQNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGD
ETQGQQPPQRRYRRNFNYRRRRPENPKPQDGKETKAADPPAENSSAPEAEQGGAE-----
------------------
>Bear | XP_026354127.1 Y-box-binding protein 1 isoform X1 [Ursus arctos]
------------------------------------------------------------
------------------------------------------------------------
-------------MS--SEAETQQPPAAP---------------PAAPALSAADTKPGTT
GSGAGSGGPGGLTSAAPAGGDKKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTA
IKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPR
RRGPPRNYQQNYQNSESGEKNEGSESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSN
PPVQGEVMEGADNQGAGEQGR-PVRQNVYRGYRPRFRRGPPRQRQPREDGNEEDKENQGD
ETQGQQPPQRRYRRNFNYRRRRPENPKPQDGKETKAADPPAENSSAPEAEQGGAE-----
------------------
>Hamster | XP_007651815.2 Y-box-binding protein 1 isoform X1 [Cricetulus griseus]
------------------------------------------------------------
------------------------------------------------------------
-------------MS--SEAETQQPPAAPA-----------------AALSAADTKPGST
GSGAGSGGPGGLTSAAPAGGDKKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTA
IKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGVPVQGSKYAADRNHYRRYPR
RRGPPRNYQQNYQNSESGEKNEGSESAPEGQAQQRRPYRRRRFPPYYMRRPYGRRPQYSN
PPVQGEVMEGADNQGAGEQGR-PVRQNMYRGYRPRFRRGPPRQRQPREDGNEEDKENQGD
ETQGQQPPQRRYRRNFNYRRRRPENPKPQDGKETKAADPPAENSSAPEAEQGGAE-----
------------------
